namespace PdfLibrary.Fonts;

/// <summary>
/// Maps Adobe glyph names to Unicode code points
/// Based on Adobe Glyph List (AGL) specification
/// </summary>
public static class GlyphList
{
    private static readonly Dictionary<string, string> _glyphToUnicode = InitializeGlyphList();

    /// <summary>
    /// Gets the Unicode character for a glyph name
    /// </summary>
    public static string? GetUnicode(string glyphName)
    {
        if (_glyphToUnicode.TryGetValue(glyphName, out string? unicode))
            return unicode;

        // Handle uniXXXX format (direct Unicode encoding)
        if (!glyphName.StartsWith("uni") || glyphName.Length != 7) return null;
        return int.TryParse(glyphName[3..], System.Globalization.NumberStyles.HexNumber, null, out int codePoint)
            ? char.ConvertFromUtf32(codePoint)
            : null;
    }

    private static Dictionary<string, string> InitializeGlyphList()
    {
        // Adobe Glyph List - common glyph name to Unicode mappings
        // This is a subset of the full AGL; full implementation would include all ~4000+ mappings
        return new Dictionary<string, string>
        {
            // Basic Latin
            ["space"] = " ",
            ["exclam"] = "!",
            ["quotedbl"] = "\"",
            ["numbersign"] = "#",
            ["dollar"] = "$",
            ["percent"] = "%",
            ["ampersand"] = "&",
            ["quotesingle"] = "'",
            ["parenleft"] = "(",
            ["parenright"] = ")",
            ["asterisk"] = "*",
            ["plus"] = "+",
            ["comma"] = ",",
            ["hyphen"] = "-",
            ["period"] = ".",
            ["slash"] = "/",

            // Numbers
            ["zero"] = "0",
            ["one"] = "1",
            ["two"] = "2",
            ["three"] = "3",
            ["four"] = "4",
            ["five"] = "5",
            ["six"] = "6",
            ["seven"] = "7",
            ["eight"] = "8",
            ["nine"] = "9",

            // More punctuation
            ["colon"] = ":",
            ["semicolon"] = ";",
            ["less"] = "<",
            ["equal"] = "=",
            ["greater"] = ">",
            ["question"] = "?",
            ["at"] = "@",

            // Uppercase Latin
            ["A"] = "A",
            ["B"] = "B",
            ["C"] = "C",
            ["D"] = "D",
            ["E"] = "E",
            ["F"] = "F",
            ["G"] = "G",
            ["H"] = "H",
            ["I"] = "I",
            ["J"] = "J",
            ["K"] = "K",
            ["L"] = "L",
            ["M"] = "M",
            ["N"] = "N",
            ["O"] = "O",
            ["P"] = "P",
            ["Q"] = "Q",
            ["R"] = "R",
            ["S"] = "S",
            ["T"] = "T",
            ["U"] = "U",
            ["V"] = "V",
            ["W"] = "W",
            ["X"] = "X",
            ["Y"] = "Y",
            ["Z"] = "Z",

            // Brackets
            ["bracketleft"] = "[",
            ["backslash"] = "\\",
            ["bracketright"] = "]",
            ["asciicircum"] = "^",
            ["underscore"] = "_",
            ["grave"] = "`",

            // Lowercase Latin
            ["a"] = "a",
            ["b"] = "b",
            ["c"] = "c",
            ["d"] = "d",
            ["e"] = "e",
            ["f"] = "f",
            ["g"] = "g",
            ["h"] = "h",
            ["i"] = "i",
            ["j"] = "j",
            ["k"] = "k",
            ["l"] = "l",
            ["m"] = "m",
            ["n"] = "n",
            ["o"] = "o",
            ["p"] = "p",
            ["q"] = "q",
            ["r"] = "r",
            ["s"] = "s",
            ["t"] = "t",
            ["u"] = "u",
            ["v"] = "v",
            ["w"] = "w",
            ["x"] = "x",
            ["y"] = "y",
            ["z"] = "z",

            // More punctuation
            ["braceleft"] = "{",
            ["bar"] = "|",
            ["braceright"] = "}",
            ["asciitilde"] = "~",

            // Latin-1 Supplement
            ["exclamdown"] = "¡",
            ["cent"] = "¢",
            ["sterling"] = "£",
            ["currency"] = "¤",
            ["yen"] = "¥",
            ["brokenbar"] = "¦",
            ["section"] = "§",
            ["dieresis"] = "¨",
            ["copyright"] = "©",
            ["ordfeminine"] = "ª",
            ["guillemotleft"] = "«",
            ["logicalnot"] = "¬",
            ["registered"] = "®",
            ["macron"] = "¯",
            ["degree"] = "°",
            ["plusminus"] = "±",
            ["twosuperior"] = "²",
            ["threesuperior"] = "³",
            ["acute"] = "´",
            ["mu"] = "µ",
            ["paragraph"] = "¶",
            ["periodcentered"] = "·",
            ["cedilla"] = "¸",
            ["onesuperior"] = "¹",
            ["ordmasculine"] = "º",
            ["guillemotright"] = "»",
            ["onequarter"] = "¼",
            ["onehalf"] = "½",
            ["threequarters"] = "¾",
            ["questiondown"] = "¿",

            // Latin Extended-A (accented characters)
            ["Agrave"] = "À",
            ["Aacute"] = "Á",
            ["Acircumflex"] = "Â",
            ["Atilde"] = "Ã",
            ["Adieresis"] = "Ä",
            ["Aring"] = "Å",
            ["AE"] = "Æ",
            ["Ccedilla"] = "Ç",
            ["Egrave"] = "È",
            ["Eacute"] = "É",
            ["Ecircumflex"] = "Ê",
            ["Edieresis"] = "Ë",
            ["Igrave"] = "Ì",
            ["Iacute"] = "Í",
            ["Icircumflex"] = "Î",
            ["Idieresis"] = "Ï",
            ["Eth"] = "Ð",
            ["Ntilde"] = "Ñ",
            ["Ograve"] = "Ò",
            ["Oacute"] = "Ó",
            ["Ocircumflex"] = "Ô",
            ["Otilde"] = "Õ",
            ["Odieresis"] = "Ö",
            ["multiply"] = "×",
            ["Oslash"] = "Ø",
            ["Ugrave"] = "Ù",
            ["Uacute"] = "Ú",
            ["Ucircumflex"] = "Û",
            ["Udieresis"] = "Ü",
            ["Yacute"] = "Ý",
            ["Thorn"] = "Þ",
            ["germandbls"] = "ß",
            ["agrave"] = "à",
            ["aacute"] = "á",
            ["acircumflex"] = "â",
            ["atilde"] = "ã",
            ["adieresis"] = "ä",
            ["aring"] = "å",
            ["ae"] = "æ",
            ["ccedilla"] = "ç",
            ["egrave"] = "è",
            ["eacute"] = "é",
            ["ecircumflex"] = "ê",
            ["edieresis"] = "ë",
            ["igrave"] = "ì",
            ["iacute"] = "í",
            ["icircumflex"] = "î",
            ["idieresis"] = "ï",
            ["eth"] = "ð",
            ["ntilde"] = "ñ",
            ["ograve"] = "ò",
            ["oacute"] = "ó",
            ["ocircumflex"] = "ô",
            ["otilde"] = "õ",
            ["odieresis"] = "ö",
            ["divide"] = "÷",
            ["oslash"] = "ø",
            ["ugrave"] = "ù",
            ["uacute"] = "ú",
            ["ucircumflex"] = "û",
            ["udieresis"] = "ü",
            ["yacute"] = "ý",
            ["thorn"] = "þ",
            ["ydieresis"] = "ÿ",

            // Ligatures
            ["fi"] = "\uFB01",
            ["fl"] = "\uFB02",

            // Punctuation
            ["endash"] = "\u2013",
            ["emdash"] = "\u2014",
            ["quoteleft"] = "\u2018",
            ["quoteright"] = "\u2019",
            ["quotesinglbase"] = "\u201A",
            ["quotedblleft"] = "\u201C",
            ["quotedblright"] = "\u201D",
            ["quotedblbase"] = "\u201E",
            ["dagger"] = "\u2020",
            ["daggerdbl"] = "\u2021",
            ["bullet"] = "\u2022",
            ["ellipsis"] = "\u2026",
            ["perthousand"] = "\u2030",
            ["guilsinglleft"] = "\u2039",
            ["guilsinglright"] = "\u203A",
            ["fraction"] = "\u2044",

            // Currency
            ["Euro"] = "\u20AC",
            ["franc"] = "\u20A3",
            ["lira"] = "\u20A4",
            ["peseta"] = "\u20A7",
            ["dong"] = "\u20AB",
            ["rupiah"] = "\u20A8",

            // Greek (uppercase)
            ["Alpha"] = "\u0391",
            ["Beta"] = "\u0392",
            ["Gamma"] = "\u0393",
            ["Delta"] = "\u0394",
            ["Epsilon"] = "\u0395",
            ["Zeta"] = "\u0396",
            ["Eta"] = "\u0397",
            ["Theta"] = "\u0398",
            ["Iota"] = "\u0399",
            ["Kappa"] = "\u039A",
            ["Lambda"] = "\u039B",
            ["Mu"] = "\u039C",
            ["Nu"] = "\u039D",
            ["Xi"] = "\u039E",
            ["Omicron"] = "\u039F",
            ["Pi"] = "\u03A0",
            ["Rho"] = "\u03A1",
            ["Sigma"] = "\u03A3",
            ["Tau"] = "\u03A4",
            ["Upsilon"] = "\u03A5",
            ["Phi"] = "\u03A6",
            ["Chi"] = "\u03A7",
            ["Psi"] = "\u03A8",
            ["Omega"] = "\u03A9",

            // Greek (lowercase)
            ["alpha"] = "\u03B1",
            ["beta"] = "\u03B2",
            ["gamma"] = "\u03B3",
            ["delta"] = "\u03B4",
            ["epsilon"] = "\u03B5",
            ["zeta"] = "\u03B6",
            ["eta"] = "\u03B7",
            ["theta"] = "\u03B8",
            ["iota"] = "\u03B9",
            ["kappa"] = "\u03BA",
            ["lambda"] = "\u03BB",
            ["mu"] = "\u03BC",
            ["nu"] = "\u03BD",
            ["xi"] = "\u03BE",
            ["omicron"] = "\u03BF",
            ["pi"] = "\u03C0",
            ["rho"] = "\u03C1",
            ["sigma"] = "\u03C3",
            ["tau"] = "\u03C4",
            ["upsilon"] = "\u03C5",
            ["phi"] = "\u03C6",
            ["chi"] = "\u03C7",
            ["psi"] = "\u03C8",
            ["omega"] = "\u03C9",

            // Math symbols
            ["summation"] = "\u2211",
            ["product"] = "\u220F",
            ["integral"] = "\u222B",
            ["radical"] = "\u221A",
            ["infinity"] = "\u221E",
            ["partialdiff"] = "\u2202",
            ["increment"] = "\u2206",
            ["notequal"] = "\u2260",
            ["lessequal"] = "\u2264",
            ["greaterequal"] = "\u2265",
            ["approxequal"] = "\u2248",

            // Arrows
            ["arrowleft"] = "\u2190",
            ["arrowup"] = "\u2191",
            ["arrowright"] = "\u2192",
            ["arrowdown"] = "\u2193",
        };
    }
}
